version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: adminadmin
      MYSQL_DATABASE: uccdemy
      MYSQL_USER: root
      MYSQL_PASSWORD: adminadmin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -padminadmin"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: golang_app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: adminadmin
      DB_NAME: uccdemy
      DB_PORT: 3306
      SECRET_JWT: 123456
      JWT_EXPIRATION_TIME: 1000

volumes:
  db_data:
